language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install tox-travis coveralls
script:
  - tox
  - coverage run --source ctci -m py.test
  - coverage report -m
after_success:
  - codecov
